### ISSUE TITLE
Callable Argument Error Zero MQ Blocks

### ISSUE THREAD

**Issue by rascustoms** [pothosware/gr-pothos#12]
The GNU Radio Zero MQ blocks do not seem to be able to be wrapped correctly in Pothos. 

![ZeroMQ Block Error](https://user-images.githubusercontent.com/13750536/57589025-271cff00-7561-11e9-9511-2a507627b63b.png)

This is running on Ubuntu 18.04 with Pothos installed from the PPA (0.6.1) and GNU Radio installed from the package manager (3.7.11) .

**Comment by guruofquality** [comment]
The first issue, the IO type is probably an issue with the parser, it should be coming up with a dropdown of IO sizes in bytes. However you can fix this one and edit the IO type (click the arrow) and enter a number in bytes (2 for short).

The second issue is kind of a bug in gnuradio, it should be using `const std::string &` or `const char *` for the address. `char *` isnt right and its not even the correct type for zeromq socket bind which takes a `const char *`. @bhilburn @marcusmueller maybe a silly bug worth fixing? 

Basically the conversion from std::string to non const char * isnt supported. I made a quick work around patch if you are interested:
```
diff --git a/GrPothosUtil.py b/GrPothosUtil.py
index 4a2dd89..87532af 100644
--- a/GrPothosUtil.py
+++ b/GrPothosUtil.py
@@ -560,9 +560,9 @@ def splitFactoryParam(factory_param):
     argPass = argName
 
     #handle special case of const char * input by replacing with std::string
-    if isConstCharStar(typeStr):
+    if isConstCharStar(typeStr) or (typeStr.count('char') == 1 and typeStr.count('*') == 1 and argName == "address"):
         typeStr = typeStr.replace('char', 'std::string').replace('*', '&')
-        argPass = argName + ".c_str()"
+        argPass = "(char *)" + argName + ".c_str()"
 
     #return c++ type, name of the argument, and code to pass into the factory
     return typeStr, argName, argPass
```

**Comment by guruofquality** [comment]
I pushed a fix for both issues, even the awkward work around for the type. I hope the @gnuradio guys can do something about the non-const thing
