### ISSUE TITLE
build error of 3.8 branch because of boost transition to std

### ISSUE THREAD

**Issue by akoun** [pothosware/gr-pothos#31]
https://github.com/pothosware/gr-pothos/blob/25c1bb491ecdce7c0ce9b584743d52e1a9166b52/GrPothosBlock/pothos_block.cc#L65

if this line is 
boost::shared_ptr<gr::block> d_msg_accept_block;

everything builds w/o error....

**Comment by ncorgan** [comment]
Thank you for the notification. However, per the README, this branch is still under early active development and should not yet be considered for use. When this changes, there will be an enforced minimum GNU Radio version where this type of change has already been set.

**Comment by akoun** [comment]
yes of course. sorry for the misunderstanding
I just thought that it is nevertheless supposed to go through build successfully independently of its working status.
