### ISSUE TITLE
Block tree structuring

### ISSUE THREAD

**Issue by akoun** [pothosware/gr-pothos#7]
It could be useful to place the gr-pothos gnuradio blocks under their own sub-tree in the Block Tree GUI panel. Something along the lines of Liquid DSP blocks that they have their own subtree.
This can be useful in order to facilitate keeping track of where individual blocks come from and which are the native pothos blocks.

EDIT1
this can be achieved if we substitute line 704 in GrPothosUtil.py
**categories = [c.replace('[Core]/', '') for c in categories]**
with
**categories = [c.replace('[Core]/', 'GNURadio/') for c in categories]**

**Comment by akoun** [comment]
this can be achieved if we substitute line 704 in GrPothosUtil.py
**categories = [c.replace('[Core]/', '') for c in categories]**
with
**categories = [c.replace('[Core]/', 'GNURadio/') for c in categories]**

**Comment by guruofquality** [comment]
not a bad idea: https://github.com/pothosware/gr-pothos/commit/551b8675a088e7e59bfffc45be6a3d2b293b635f

same for liquid https://github.com/pothosware/PothosLiquidDSP/commit/2dc20d543edfdb0238fdd1fd96e9e2209ff0e3e0
